version: '3.8'

services:
  web:
    image: your-dockerhub-username/items-manager:latest
    container_name: items-manager
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - APP_ENV=production
    volumes:
      - ./static:/app/static  