version: '3.8'

services:
  web:
    image: thefarmguy/todofastapi:1.0
    container_name: todofastapi
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - APP_ENV=production
    volumes:
      - ./static:/app/static  